### PR TITLE
Fix for fritz connector

### LINKED ISSUE #4187: Fritz connector is not working anymore
The problem is the connector seems to be outdated.

Also the livestream website doesn't display the current playback information anymore.
So we can't scrape the track and artist...

### PR DESCRIPTION
**Pull request by Ceddicedced**
Fixed and tested the fritz connector

**Describe the changes you made**
All selectors where overhauled so they are modern and working again.

Resolves  #4187

### CODE REVIEW

File: src/connectors/fritz.ts [hunk 1]
```diff
@@ -1,9 +1,28 @@
...
-Connector.isPlaying = () => Util.hasElementClass('.player', 'player_playing');
+Connector.pauseButtonSelector = '.audioplayer-playing';
+
+const filter = MetadataFilter.createFilter({
+	artist: (artist) => {
+		// If the artist string contains a semicolon, split the string by the semicolon
+		// and return the first element (the part of the string before the semicolon).
+
+		// Replace .feat with a semicolon
+		artist = artist.replace('.feat', ';');
```
Comment (inverse) [inline src/connectors/fritz.ts:17]: Looks like you need to fix this by perhaps using another variable within the function. 

e.g. `const updatedArtist = artist.replace('.feat', ';');` and using this within the function?

**Review by inverse — CHANGES_REQUESTED** [review]

File: src/connectors/fritz.ts (hunk 1 above)
Comment (Ceddicedced) [reply src/connectors/fritz.ts]: Yeah tbj i just ignored the eslint error. But i fixed it accordingly.

**Review by inverse — APPROVED** [review]
Thanks for the contribution!
