### PR TITLE
Fix image url helper

### LINKED ISSUE #3769: Sirius XM won't scrobble in Google Chrome. Windows 10.
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

### PR DESCRIPTION
**Pull request by yayuyokitano**
Checks off a little edge case that was missed.
Closes #3769 as this was the underlying cause of that connector not working.

### CODE REVIEW

File: src/core/content/util.ts [hunk 1]
```diff
@@ -496,7 +496,7 @@ export function extractImageUrlFromSelectors(
 		return null;
 	}
 	const elements = queryElements(selectors);
-	if (!elements) {
+	if (!elements || !elements.length) {
```
Comment (inverse) [inline src/core/content/util.ts:499]: Still learning this TS syntax - just to something more akin to `elements.length === 0

**Review by inverse — APPROVED** [review]

File: src/core/content/util.ts (hunk 1 above)
Comment (yayuyokitano) [reply src/core/content/util.ts:499]: Did it out of habit. It's essentially equivalent to elements.length === 0.
Its a bit of a more javascripty way of doing things, as if _somehow_ (javascript) we end up not actually having an array here it will still short circuit and not error.
I don't think it should be possible for there to not be an array at this point though
