### PR TITLE
Poolsuite scrobbling fixed via Media Session API (fixes #5375)

### LINKED ISSUE #5375: Poolsuite.net connector not working
**Describe the bug**
 WS not scrobbling from Poolsuite.net

**How to reproduce**
* Go to ['Poolsuite'](https://poolsuite.net/)
* Click on Play
* Web Scrobbler does not detect the music

**Expected behavior**
 Web Scrobbler detects the music

**Environment (please complete the following information)**
-   OS: Mac OSX 15.4.1
-   Browser: Firefox 139.0b10 
-   Extension version:  3.10.0

### PR DESCRIPTION
**Pull request by edelstone**
**Describe the changes you made**

Replaced the old Poolsuite DOM-scraping connector with Media Session API support. Poolsuite now exposes track and artist via `navigator.mediaSession.metadata`, so Web Scrobbler can read it directly without brittle selectors.

**Additional context**

Fixes #5375.

Tested on [poolsuite.net](https://poolsuite.net) in Chrome/Brave for Mac. Track and artist update correctly when skipping tracks and scrobble normally.

Apologies for the [duplicate PR](https://github.com/web-scrobbler/web-scrobbler/pull/5779); I deleted my fork before you completed review. This is an identical fix as previously submitted.

### CODE REVIEW

File: src/connectors/poolsuite.ts [hunk 1]
```diff
@@ -1,11 +1,4 @@
...
-Connector.playerSelector = '.inner-size';
-Connector.trackSelector = '.current-track h3';
-Connector.artistSelector = '.current-track h2';
-Connector.currentTimeSelector = '.timer span:nth-child(1)';
-Connector.durationSelector = '.timer span:nth-child(2)';
-
-Connector.scrobblingDisallowedReason = () =>
-	Connector.getTrack() === 'Loading...' ? 'IsLoading' : null;
+Connector.playerSelector = 'body';
+Connector.useMediaSessionApi();
```
Comment (inverse) [inline src/connectors/poolsuite.ts:4]: When testing I noticed including `Connector.useTabAudibleApi();` allows us to react to the play state of the site?

Comment (edelstone) [reply src/connectors/poolsuite.ts:4]: Yes, of course. Added `Connector.useTabAudibleApi()` to improve play/pause detection via tab audio state.

**Review by inverse — APPROVED** [review]

**Review by inverse — APPROVED** [review]
Thanks for the contribution!
